
package com.github.peholmst.soapsamples.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactWS", targetNamespace = "http://server.soapsamples.peholmst.github.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactWS {


    /**
     * 
     * @param contact
     * @return
     *     returns com.github.peholmst.soapsamples.server.Contact
     * @throws NoSuchContactException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.UpdateResponse")
    @Action(input = "http://server.soapsamples.peholmst.github.com/ContactWS/updateRequest", output = "http://server.soapsamples.peholmst.github.com/ContactWS/updateResponse", fault = {
        @FaultAction(className = NoSuchContactException_Exception.class, value = "http://server.soapsamples.peholmst.github.com/ContactWS/update/Fault/NoSuchContactException")
    })
    public Contact update(
        @WebParam(name = "contact", targetNamespace = "http://server.soapsamples.peholmst.github.com/")
        Contact contact)
        throws NoSuchContactException_Exception
    ;

    /**
     * 
     * @return
     *     returns com.github.peholmst.soapsamples.server.Contact
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.CreateResponse")
    @Action(input = "http://server.soapsamples.peholmst.github.com/ContactWS/createRequest", output = "http://server.soapsamples.peholmst.github.com/ContactWS/createResponse")
    public Contact create();

    /**
     * 
     * @return
     *     returns java.util.List<com.github.peholmst.soapsamples.server.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.FindAllResponse")
    @Action(input = "http://server.soapsamples.peholmst.github.com/ContactWS/findAllRequest", output = "http://server.soapsamples.peholmst.github.com/ContactWS/findAllResponse")
    public List<Contact> findAll();

    /**
     * 
     * @param uuid
     * @return
     *     returns com.github.peholmst.soapsamples.server.Contact
     * @throws NoSuchContactException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByUuid", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.FindByUuid")
    @ResponseWrapper(localName = "findByUuidResponse", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.FindByUuidResponse")
    @Action(input = "http://server.soapsamples.peholmst.github.com/ContactWS/findByUuidRequest", output = "http://server.soapsamples.peholmst.github.com/ContactWS/findByUuidResponse", fault = {
        @FaultAction(className = NoSuchContactException_Exception.class, value = "http://server.soapsamples.peholmst.github.com/ContactWS/findByUuid/Fault/NoSuchContactException")
    })
    public Contact findByUuid(
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid)
        throws NoSuchContactException_Exception
    ;

    /**
     * 
     * @param uuid
     * @throws NoSuchContactException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteByUuid", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.DeleteByUuid")
    @ResponseWrapper(localName = "deleteByUuidResponse", targetNamespace = "http://server.soapsamples.peholmst.github.com/", className = "com.github.peholmst.soapsamples.server.DeleteByUuidResponse")
    @Action(input = "http://server.soapsamples.peholmst.github.com/ContactWS/deleteByUuidRequest", output = "http://server.soapsamples.peholmst.github.com/ContactWS/deleteByUuidResponse", fault = {
        @FaultAction(className = NoSuchContactException_Exception.class, value = "http://server.soapsamples.peholmst.github.com/ContactWS/deleteByUuid/Fault/NoSuchContactException")
    })
    public void deleteByUuid(
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid)
        throws NoSuchContactException_Exception
    ;

}
