
package com.github.peholmst.soapsamples.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ContactWSService", targetNamespace = "http://server.soapsamples.peholmst.github.com/", wsdlLocation = "http://localhost:8080/server/ContactWSService?wsdl")
public class ContactWSService
    extends Service
{

    private final static URL CONTACTWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTACTWSSERVICE_EXCEPTION;
    private final static QName CONTACTWSSERVICE_QNAME = new QName("http://server.soapsamples.peholmst.github.com/", "ContactWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/server/ContactWSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTACTWSSERVICE_WSDL_LOCATION = url;
        CONTACTWSSERVICE_EXCEPTION = e;
    }

    public ContactWSService() {
        super(__getWsdlLocation(), CONTACTWSSERVICE_QNAME);
    }

    public ContactWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTACTWSSERVICE_QNAME, features);
    }

    public ContactWSService(URL wsdlLocation) {
        super(wsdlLocation, CONTACTWSSERVICE_QNAME);
    }

    public ContactWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTACTWSSERVICE_QNAME, features);
    }

    public ContactWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContactWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContactWS
     */
    @WebEndpoint(name = "ContactWSPort")
    public ContactWS getContactWSPort() {
        return super.getPort(new QName("http://server.soapsamples.peholmst.github.com/", "ContactWSPort"), ContactWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContactWS
     */
    @WebEndpoint(name = "ContactWSPort")
    public ContactWS getContactWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soapsamples.peholmst.github.com/", "ContactWSPort"), ContactWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTACTWSSERVICE_EXCEPTION!= null) {
            throw CONTACTWSSERVICE_EXCEPTION;
        }
        return CONTACTWSSERVICE_WSDL_LOCATION;
    }

}
