
package com.github.peholmst.soapsamples.server;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchContactException", targetNamespace = "http://server.soapsamples.peholmst.github.com/")
public class NoSuchContactException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchContactException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchContactException_Exception(String message, NoSuchContactException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoSuchContactException_Exception(String message, NoSuchContactException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.github.peholmst.soapsamples.server.NoSuchContactException
     */
    public NoSuchContactException getFaultInfo() {
        return faultInfo;
    }

}
